insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (1, 'Hybrid Ladyslipper', 21750, 'Césped Real', 1, 1);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (2, 'Hemp', 26018, 'Césped Sintético', 2, 2);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (3, 'Woodland Islandfern', 34414, 'Césped Real', 3, 3);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (4, 'Panicledleaf Ticktrefoil', 21421, 'Césped Real', 4, 4);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (5, 'Bacury', 36065, 'Césped Sintético', 5, 5);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (6, 'Ridged Yellow Flax', 23636, 'Césped Real', 6, 6);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (7, 'Carolina Scalystem', 33435, 'Césped Real', 7, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (8, 'Rocky Mountain Whitethroat', 30811, 'Césped Real', 8, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (9, 'Spreading Wheatgrass', 36272, 'Césped Real', 9, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (10, 'Woolly Locoweed', 23104, 'Césped Sintético', 10, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (11, 'Candle Snuffer Moss', 21083, 'Césped Real', 11, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (12, 'Jonesville Springbeauty', 29194, 'Césped Sintético', 12, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (13, 'Lilyturf', 31233, 'Césped Sintético', 13, 13);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (14, 'Constance''s Rockcress', 31717, 'Césped Sintético', 14, 14);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (15, 'Hala Pepe', 30012, 'Césped Sintético', 15, 15);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (16, 'Giant Spiderwort', 36739, 'Césped Real', 16, 16);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (17, 'Watson''s Fleabane', 21682, 'Césped Real', 17, 17);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (18, 'Trumpet Creeper', 27258, 'Césped Sintético', 18, 18);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (19, 'Woolly Hawkweed', 38953, 'Césped Sintético', 19, 19);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (20, 'Sphagnum', 32649, 'Césped Sintético', 20, 20);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (21, 'Sphagnum', 39113, 'Césped Real', 21, 21);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (22, 'White Penstemon', 32585, 'Césped Sintético', 22, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (23, 'Hartweg''s Sundrops', 20997, 'Césped Real', 23, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (24, 'Woodrush', 26857, 'Césped Sintético', 24, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (25, 'Florida Pimpernel', 25823, 'Césped Real', 25, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (26, 'San Francisco Spineflower', 31489, 'Césped Real', 26, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (27, 'Field Mustard', 28694, 'Césped Sintético', 27, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (28, 'Elmleaf Blackberry', 28336, 'Césped Sintético', 28, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (29, 'Lost River Draba', 20655, 'Césped Sintético', 29, 29);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (30, 'Thinstem Lady''s Mantle', 20779, 'Césped Real', 30, 30);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (31, 'Longstalk Starwort', 36271, 'Césped Real', 31, NULL);
insert into Estadios (idEstadio, nombre, capacidad, tipoDeSuperficie, idCiudad, idEquipo) values (32, 'Ottertail Pass Saxifrage', 36284, 'Césped Real', 32, NULL);
