insert into Rondas (idRonda, nombre, idFase) values (1, 'Grupo A', 1);
insert into Rondas (idRonda, nombre, idFase) values (2, 'Grupo B', 1);
insert into Rondas (idRonda, nombre, idFase) values (3, 'Grupo C', 1);
insert into Rondas (idRonda, nombre, idFase) values (4, 'Grupo D', 1);
insert into Rondas (idRonda, nombre, idFase) values (5, 'Grupo E', 1);
insert into Rondas (idRonda, nombre, idFase) values (6, 'Grupo F', 1);
insert into Rondas (idRonda, nombre, idFase) values (7, 'Grupo G', 1);
insert into Rondas (idRonda, nombre, idFase) values (8, 'Grupo H', 1);
insert into Rondas (idRonda, nombre, idFase) values (9, 'Octavos', 2);
insert into Rondas (idRonda, nombre, idFase) values (10, 'Cuartos', 2);
insert into Rondas (idRonda, nombre, idFase) values (11, 'Semifinal', 2);
insert into Rondas (idRonda, nombre, idFase) values (12, 'Final', 2);
